#! /bin/sh

# App settings
#export TERM="termite"
#export LAUNCH="rofi -show run"
#export BROWSE="firefox"

# Kill
killall picom 
killall feh
killall sxhkd
killall polybar

# Autostart environment
picom -b &
#flashfocus &
feh --bg-scale $HOME/photos/waves.jpg
#hsetroot -solid '#282a36' &
sxhkd &

bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7 8 9 10 

# Autostart user applications, add new programs to $programs array
programs=(
	"keepassxc"
	"firefox"
	)

for program in ${programs[@]}; do
	if ! pgrep $program > /dev/null 
	then
		$program &
	fi
done

# Misc:
xsetroot -cursor_name left_ptr
xset s 120 
xset dpms 300
xss-lock -- betterlockscreen -l &

# Polybar
$HOME/.config/polybar/launch.sh 

# Window config
bspc config focus_follows_pointer 	true
bspc config border_width		2 
bspc config window_gap          	10
bspc config bottom_padding		0

# Layout config
#bspc config automatic_scheme alternate
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true

# Color config
bspc config normal_border_color		"#44475a"
bspc config focused_border_color	"#8be9fd"
bspc config active_border_color     	"#6272a4"
bspc config presel_feedback_color	"#4a697d"

# Default locations for apps
bspc rule -a KeePassXC desktop=^5 follow=on state=floating
bspc rule -a firefox desktop=^2 follow=on
bspc rule -a Thunderbird desktop=^7 follow=on


